services:
  spark-notebook:
    build: .
    container_name: spark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041-4050:4041-4050"
    volumes:
      - ./notebooks:/workspace/notebooks
    working_dir: /workspace